[general]
library_name = "libanari"
output_file_path = "../src/LibANARI.jl"
module_name = "LibANARI"
jll_pkg_name = "ANARI_SDK_jll"
export_symbol_prefixes = ["ANARI", "anari"]

use_julia_native_enum_type = true

[codegen]
use_ccall_macro = true
always_NUL_terminated_string = true

[codegen.macro]
macro_mode = "aggressive"
